


on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Query Dependabot Alerts 
  # You may pin to the exact commit or the version.
  # uses: pwned-17/check-dependabot@d28fd56c05709ee27836b49b08193de299795048
        uses: pwned-17/check-dependabot@v1.2.9
        with:
    # GitHub Personal Access Token
             github_personal_token: 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
